import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import AnimatedContent from "@components/AnimatedContent/AnimatedContent";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Roster Portfolio",
  description: "Generated by create next app",
};

function App({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <nav className="navbar">
        <div className="navbar-container">
          <Link href="/" className="logo">
            <h1 style={{ fontSize: "1.4rem" }}>roster</h1>
          </Link>
          <div className="profile-section">
            <div className="avatar">
              <Image
                src="/images/profilePhoto.jpg"
                alt="Profile"
                width={32}
                height={32}
                className="profile-image"
                priority
                quality={50}
              />
            </div>
          </div>
        </div>
      </nav>
      <div className="main-grid">
        <div className="sidebar-left"></div>
        <AnimatedContent>{children}</AnimatedContent>
        <div className="sidebar-right"></div>
      </div>
    </>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <App>{children}</App>
        </StoreProvider>
        ;
      </body>
    </html>
  );
}
